/*
 * ultrasonic.c
 *
 *  Created on: Oct 16, 2024
 *      Author: Hayam
 */
# include "icu.h"
# include "ultrasonic.h"
# include "gpio.h"
# include "util/delay.h"
# include "std_types.h"
/***********************************************************/
uint8 edge_count =0;
uint32 recieve_time=0;
uint16 distance=0;
ICU_ConfigType ICU_Configrution={F_CPU_8,RAISING};
/***********************************************************/
void Ultrasonic_init(void)
{
	/*Initialize the ICU driver as required.*/
	ICU_init(&ICU_Configrution);
	/*Set up the ICU callback function.*/
	ICU_setCallBack(Ultrasonic_edgeProcessing);
	/*Set the direction for the trigger pin as output through the GPIO driver.*/
	GPIO_setupPinDirection(ULTRASONIC_TR_PORT_ID,ULTRASONIC_TR_PIN_ID,PIN_OUTPUT);
	GPIO_setupPinDirection(ULTRASONIC_ECHO_PORT_ID,ULTRASONIC_ECHO_PIN_ID,PIN_INPUT);

}
void Ultrasonic_Trigger(void)
{
	/*Send the trigger pulse to the ultrasonic sensor.*/
	GPIO_writePin(ULTRASONIC_TR_PORT_ID,ULTRASONIC_TR_PIN_ID,LOGIC_HIGH);
	_delay_us(20);
	GPIO_writePin(ULTRASONIC_TR_PORT_ID,ULTRASONIC_TR_PIN_ID,LOGIC_LOW);
}
uint16 Ultrasonic_readDistance(void)
{
	/* Send the trigger pulse by using the Ultrasonic_Trigger function.*/
	Ultrasonic_Trigger();
	/*Start the measurement process via the ICU driver*/
	distance=(recieve_time) / 117.6;
	return distance;
}
void Ultrasonic_edgeProcessing(void)
{
	/*This is the callback function called by the ICU driver.*/
	/*It calculates the high time (pulse time) generated by
	the ultrasonic sensor. */
	edge_count++;
	if(1==edge_count)
	{
		ICU_clearTimerValue();
		ICU_setEdgeDetectionType(FALLING);
	}
	else if(2==edge_count)
	{
		recieve_time=ICU_getInputCaptureValue();
		ICU_setEdgeDetectionType(RAISING);
	}
	else
	{
		edge_count =0;

	}
}
